### PR TITLE
add OrdinaryDiffEqCore weakdep

### PR DESCRIPTION
**Pull request by isaacsas**
I don't know if this is the version to use, or if something more is required (like updating the registry manually).

### CODE REVIEW

**Comment by ChrisRackauckas** [comment]
We might want to yank the previous release or put this bound on it.

**Comment by isaacsas** [comment]
Whatever you want to do. I’m not sure what that would entail (a PR that modifies the general registry in some way I assume)?

**Comment by isaacsas** [comment]
Do we know that this fixes @baggepinnen’s issue?

**Comment by ChrisRackauckas** [comment]
it would need a registry yank on the last release to force it, but other than that it should.

**Comment by isaacsas** [comment]
Can you make a 3.9.1 release then? I’ll make the PR to yank 3.9 now.

**Comment by isaacsas** [comment]
https://github.com/JuliaRegistries/General/pull/114513

**Pull request merged**
