### PR TITLE
Add `LinearizingSavingCallback`

### PR DESCRIPTION
**Pull request by staticfloat**
Provides a saving callback that inserts interpolation points into your signal such that a naive linear interpolation of the resultant saved values will be within `abstol`/`reltol` of the higher-order interpolation of your solution.  This essentially makes a time/space tradeoff, where more points in time are saved, costing more memory, but interpolation is incredibly cheap and downstream algorithm complexity is reduced by not needing to bother with multiple interpolation types.

The algorithm internally checks 3 equidistant points between each time point to determine goodness of fit versus the linearly interpolated function; this should be sufficient for interpolations up to the 4th order, higher orders may need more points to ensure good fit.  This has not been implemented yet.

### CODE REVIEW

**Comment by ChrisRackauckas** [comment]
Needs tests.

**Comment by staticfloat** [comment]
Looking a little bit further into the `rigidbody` different, it appears that setting denser `tstops` changes the solution of that problem significantly.  We are solving to `abstol=1e-6` and `reltol=1e-3`, and while the error starts out well under that, it grows steadily over time until it reaches `1e-2`.  If I crank the `abstol` and `reltol` down by 3 orders of magnitude, the resultant errors drop a concordant amount.  I suppose this falls under the same aegis of a lack of global error control and that inserting a bunch of `tstop`'s can change the behavior of the solve significantly?  Should I not be testing by re-solving with new `tstops` but instead be comparing against a post-solve interpolation with `t_upsampled`?

**Comment by ChrisRackauckas** [comment]
> Looking a little bit further into the rigidbody different, it appears that setting denser tstops changes the solution of that problem significantly. We are solving to abstol=1e-6 and reltol=1e-3, and while the error starts out well under that, it grows steadily over time until it reaches 1e-2. If I crank the abstol and reltol down by 3 orders of magnitude, the resultant errors drop a concordant amount. I suppose this falls under the same aegis of a lack of global error control 

Yes exactly.

> inserting a bunch of tstop's can change the behavior of the solve significantly?

Yes, it decreases `dt` and improves the solution

> Should I not be testing by re-solving with new tstops but instead be comparing against a post-solve interpolation with t_upsampled?

Yes, with new tstops you can only assume it has not changed the solution more than the current (global) error. Not changing tstops is probably a better idea for testing unless the tolerance is sufficiently small

**Comment by staticfloat** [comment]
Okay, great.  I've updated the tests.  If you're happy with this, I think it's good to merge.

**Review by ChrisRackauckas — APPROVED** [review]

**Pull request merged**
